name: Deploy Docker image to EC2
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  host_name: ec2-54-163-199-140.compute-1.amazonaws.com
  user_name: ec2-user

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      image_tag: techco:${{ github.sha }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t $image_tag
    - name: Save docker image as file
      run: docker save $image_tag > techco.tar
    - name: Copy docker image to ec2
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.host_name}}
        username: ${{ env.user_name}}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: techco.tar
        target: /home/ec2-user
    - name: Start Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.host_name}}
        username: ${{ env.user_name}}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker load -i /home/ec2-user/techco.tar