name: Deploy Docker image to EC2
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  host_name: ec2-54-221-97-19.compute-1.amazonaws.com
  user_name: ec2-user

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      image_tag: techco:${{ github.sha }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t $image_tag
    - name: Save docker image as file
      run: docker save $image_tag > deploy/techco.tar
    - name: Copy files to ec2
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.host_name}}
        username: ${{ env.user_name}}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: deploy/*
        target: /home/ec2-user/deploy
        overwrite: true
    - name: Start Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.host_name}}
        username: ${{ env.user_name}}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker load -i /home/ec2-user/deploy/techco.tar
          sed -i "s/IMAGE_NAME/${{ env.image_tag}}/g" /home/ec2-user/deploy/compose.yaml
          if [ ! -f "/etc/systemd/system/techco.service" ]; then
              sudo cp /home/ec2-user/deploy/techco.service /etc/systemd/system/
              sudo systemctl enable techco
              sudo systemctl start techco
          else
              sudo systemctl restart techco
          fi
          # cleaup
          rm /home/ec2-user/deploy/techco.tar

